sonar.projectKey=niikkhilsharma_embeded-ai-chatbot
sonar.organization=niikkhilsharma


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=embeded-ai-chatbot
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.projectName=embeded-ai-chatbot
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/out/**,**/samples/**,**/dummy-data/**,**/.cursor/**,**/package-lock.json,**/public/assets/**
